### ISSUE TITLE
Status Bar height for iPhone X

### ISSUE THREAD

**Issue by karvulf** [benevbright/react-navigation-collapsible#81] opened 2019-07-15 14:02 UTC
I am confused about the extra height for ios devices. If I use react-navigation-collapsible for an I-Phone-X Emulator, my header is bigger than it should be. I looked into the code and found this function
```
const getStatusBarHeight = isLandscape => {
  if (Platform.OS === 'ios') {
    if (isLandscape) return 0;
    return IS_IPHONE_X ? 44 : 20;
  } else if (Platform.OS === 'android') return androidStatusBarHeight;
  else return 0;
```
The function is called to set the height of the header. Why does an ios-device gets extra height especially iphoneX, if there is no landscape mode?

**Comment by benevbright** [comment] 2019-07-15 14:05
Hi, thanks for the issue.
Can you post the screenshot of your iPhone simulator as well?

**Comment by karvulf** [comment] 2019-07-15 14:23
The yellow area is the statusbarheight that I get because of the function "getStatusBarHeight"

![Bildschirmfoto 2019-07-15 um 16 21 23](https://user-images.githubusercontent.com/36191072/61223318-b048e180-a71c-11e9-8eb4-6612e9fae27c.png)
![Bildschirmfoto 2019-07-15 um 16 21 32](https://user-images.githubusercontent.com/36191072/61223319-b048e180-a71c-11e9-9144-08b4a0dc8a40.png)

**Comment by benevbright** [comment] 2019-07-15 14:26
It seems to be happening because this module is not supporting one of latest version of `react-native` or `react-navigation`.

Could you give your versions of those two modules?

**Comment by karvulf** [comment] 2019-07-15 14:32
Yes,
    "react-native": "^0.59.8",
    "react-navigation": "^3.9.1",
    "react-navigation-collapsible": "^3.0.3",

**Comment by benevbright** [comment] 2019-08-18 20:51
Hi, I'm sorry for the late reply. 
I updated example's RN and react-navigation to up to date and tried to reproduce your issue. 
But I couldn't make it. 

What I guess it that you're using your custom header.
I'll close this issue, for now, please reopen it if this issue is still valid.

**Closed by benevbright** 2019-08-18 20:51 UTC
Labels: bug

**Comment by Thierno2sow** [comment] 2020-01-23 22:34
hey i have the same problem on a iphone XR

**Comment by benevbright** [comment] 2020-01-23 22:43
@Thierno2sow 

Hi, do you use a custom header or default header? (the custom header is not supported)
Can you try with the `/example` and see if the issue persists?

And please give your `react-navigation-stack` version. (react-navigation-stack@v2 is not supported)

**Comment by Thierno2sow** [comment] 2020-01-23 22:45
i am using a custom header i think that might be the problem then, will this be fixed on the lib anytime soon or no

**Comment by benevbright** [comment] 2020-01-23 22:52
@Thierno2sow Thanks for your response. 
I will be working on for the custom header but will be done in `react-navigation-collapsible@v5`, which is compatible with `react-navigation@v5 (next)`.
But not 100% sure for now if it's doable. I need to give a shot.

**Comment by Thierno2sow** [comment] 2020-01-24 14:30
thank you and yes i am useing "react-navigation-collapsible": "^3.0.3",

**Comment by benevbright** [comment] 2020-01-24 21:54
@Thierno2sow 
Thanks again. 
And sorry about it... No plan to update v3 😥

**Comment by Thierno2sow** [comment] 2020-01-27 14:34
ok thank you no problem we will for the react-navigation@v5 to be out and make the update

**Comment by ozerty** [comment] 2020-04-07 20:02
Hi @ benevbright any chance to have a patch for v3.
We are in final release of our app, and it will be a huge risk for us to update to react-navigation@v5.

Thanks

**Comment by benevbright** [comment] 2020-04-07 20:23
Hi, @ozerty 
I don't think I could manage the time. And this feature hasn't been implemented on v5 yet either. 🙈

One solution could be using a branch in this PR. https://github.com/benevbright/react-navigation-collapsible/pull/77
(It's not on my repo, you need to use @misaku 's repo)
I'm sorry about it.
