### ISSUE TITLE
I have used cat demo. When I scroll slowly towards header i can see entire scroll view getting vibrated. Could you please tell me how to fix it

### ISSUE THREAD

**Issue by Pamu2018** [benevbright/react-navigation-collapsible#62] opened 2019-01-29 19:13 UTC

**Comment by benevbright** [comment] 2019-01-29 19:17
Hi, thanks for your issue.
It's actually a bug from `react-native` and it occurs only on Android.

Check those out.
https://github.com/facebook/react-native/issues/15445
https://github.com/facebook/react-native/issues/19725

Hi, I'm looking into it, though.

**Comment by benevbright** [comment] 2019-01-31 12:59
https://github.com/facebook/react-native/issues/15445#issuecomment-321721259

Here is a workaround and it works. I will write `postinstall` script for example.
But I don't think you can use it if you're using Expo.

**Comment by benevbright** [comment] 2019-02-04 23:04
Unfortunately, I was wrong. 
It doesn't seem to a workaround.

**Comment by davidkalosi** [comment] 2019-02-11 20:23
hi @benevbright any new development on that issue?

**Comment by Ashish-ish** [comment] 2019-02-19 14:13
HI @benevbright  any updates

**Comment by ddedic** [comment] 2019-02-28 14:27
+1

**Comment by benevbright** [comment] 2019-03-08 11:23
Hi.
Sorry, this issue is not fixed yet on `react-native`.
I was thinking to fix react-native but I couldn't manage time for that.
Tbh, I'm also still waiting 😢

**Comment by Albert0405** [comment] 2019-03-17 01:50
any solution for this?

**Comment by benevbright** [comment] 2019-03-19 23:04
@Albert0405 Hi,
I saw your comment on react-native issue. https://github.com/facebook/react-native/issues/21801#issuecomment-474352405

I really appreciate. 
But unfortunately, it doesn't work for this module. I tried that aproach already though and I gave a shot today again but no luck.

Could you test your code with the example of this module? 
You can test it by simply modify the code in `node_modules/react-navigation-collapsible/index.js`.

https://github.com/benevbright/react-navigation-collapsible/blob/8dc33e36b25ea71c2f9cd5f9b2d51895ccd88ffe/index.js#L339-L344

I tried changing here like below.
```
<Animated.View style={{ position: 'absolute', width: '100%', height: '100%', zIndex: 999, top: 0, marginTop: paddingHeight, marginBottom: -paddingHeight, transform: [{ translateY }] }}>
              <MaterialTopTabNavigator
                screenProps={this.props}
                navigation={this.props.navigation}
              />
            </Animated.View>
```

**Comment by brunohkbx** [comment] 2019-05-03 02:21
Hey @benevbright, any update on this?
I had to implement this feature but this flickering problem made it not suitable for a production release :(

**Comment by fokoz** [comment] 2019-07-12 11:21
Animation when collapsing is very laggy and shaking even on iOS, does anyone face this ?

**Comment by kartikpr** [comment] 2019-08-13 18:52
Any updates?

**Comment by benevbright** [comment] 2019-08-14 08:20
I heard it's fixed on RN 60.4. https://github.com/react-native-community/releases/issues/130#issuecomment-519191161
(But other says it's not. I guess I need to test)
I'll make some time for testing this (maybe weekend).

**Comment by kartikpr** [comment] 2019-08-15 05:13
I hope its got fixed, thanks for the prompt reply.
Please keep us posted.

**Comment by benevbright** [comment] 2019-08-18 20:56
I just updated example's `react-native` to 0.60.5 which is latest. 
But the issue is still happening. I'm sorry about it.

#### GIF
![Aug-18-2019 6-19-48 PM](https://user-images.githubusercontent.com/916690/63230322-52bc1f00-c20b-11e9-9279-96121139d379.gif)

**Comment by vinodache** [comment] 2019-09-25 18:02
Hey, I do not have a fix yet but was wondering how twitter or instagram handled the similar widget in their UX. I thought they use react native too. Any one has an idea. For instance both twitter and instagram uses a sticky tab with a scrollable header.

Cheers
Vinod

**Comment by benevbright** [comment] 2019-12-27 10:38
@vinodache I think it only works without having `translateY` on the ScrollView/Flatlist. There is no way to resolve this without the real fix from RN.
I can only guess that they're using `paddingTop` instead.
But I can't do that because we're using `react-navigation`'s tab navigator.

**Comment by benevbright** [comment] 2020-10-16 12:13
The bug never gets fixed on React Native.

**Closed by benevbright** 2020-10-16 12:13 UTC
Labels: bug-react-native, help wanted
