### ISSUE TITLE
New version, a few questions?

### ISSUE THREAD

**Issue by emmx** [benevbright/react-navigation-collapsible#63] opened 2019-01-31 06:53 UTC
I'm testing the latest changes and so far everything work as expected, really nice job! A few questions here so I can further tweak this lib for my app.

1. Is there a workaround for the flickering bug in Android (reported in #62)? Have you used this lib on production already with this bug? It's pretty annoying and it looks like it won't be fixed anytime soon by the RN team (the bug was reported back in 2017).

2. It would be nice to have a prop to disable the header opacity animation (ie, remove the opacity in line [89](https://github.com/benevbright/react-navigation-collapsible/blob/master/index.js#L89))

3. More importantly, why is the content below the header hidden immediately after you start scrolling? I expect it to remain visible until the header is fully collapsed/hidden or at least to have a prop to enable that. Any way to disable this? I'm trying to change this behavior myself but I'm not yet sure what changes are needed or what lines are really responsible for this.

**Comment by benevbright** [comment] 2019-01-31 12:40
Hey, @emmx Thanks for the discussion.
1. I'm looking into it.
2. good idea. 
3. I'm sorry, I don't understand clearly. what is `content` and which sample example are you talking about?

**Comment by benevbright** [comment] 2019-01-31 12:59
1. https://github.com/facebook/react-native/issues/15445#issuecomment-321721259

Here is a workaround and it works. I will write `postinstall` script for example.
But I don't think you can use it if you're using Expo.

**Comment by emmx** [comment] 2019-02-01 09:34
I'm not using Expo so it probably works for me, thanks!

Regarding number 3, have a look at the two GIFs below. Pay attention to the "About" section on the first one, which is right below the tabs. See how it's not hidden until it goes beyond the screen? On the other hand this lib would hide it immediately as you start scrolling, check the second recording.

![e_n](https://user-images.githubusercontent.com/1238560/52114160-10721e00-25ea-11e9-8440-95d7cea4d814.gif)

![peek 2019-02-01 06-31](https://user-images.githubusercontent.com/1238560/52114549-1ae0e780-25eb-11e9-9d0b-2fb11bd79276.gif)

**Comment by benevbright** [comment] 2019-02-01 09:41
Oh, now I got it. Thanks for the kind explanation. It's related to https://github.com/benevbright/react-navigation-collapsible/issues/64.

If you set `safeBounceHeight` as 0, it would work as you expected. 
But the thing is that it's not happy with iOS's built-in bounce scroll and that's why I had to put `safeBounceHeight` there.

**Comment by emmx** [comment] 2019-02-01 10:12
I just set `safeBounceHeight = 0` in line [35](https://github.com/benevbright/react-navigation-collapsible/blob/master/index.js#L35) but it doesn't seem to alter how it works, in fact it looks exactly the same while scrolling.

**Comment by benevbright** [comment] 2019-02-01 10:14
Hm.. It should work...
I'm sorry. one more time.
Could you make sure your `node_module` folder is properly updated?

**Comment by emmx** [comment] 2019-02-01 10:15
Yes, I thought it may be the case but nope, I'm logging its value right below that line and it's 0. Any other idea?

**Comment by benevbright** [comment] 2019-02-01 11:19
Ok, I could reproduce it. It's actually not exactly the same as before, but I could see your problem on my side too.
I think velocity is different somehow between scrolling and collapsing.

But, I think it could be fixed easily because of iOS's bounce. We can't just forget about iOS. What do you think?

**Comment by emmx** [comment] 2019-02-01 12:21
I'm not sure what the problem with iOS bounce is. Maybe we should force bounce=false as mentioned in #64? Don't know really, I haven't tested this on iOS yet.

Regarding this issue in particular, did you figure out what is causing the difference in velocity?

**Comment by emmx** [comment] 2019-02-03 07:04
> 1. [facebook/react-native#15445 (comment)](https://github.com/facebook/react-native/issues/15445#issuecomment-321721259)
> 
> Here is a workaround and it works. I will write `postinstall` script for example.
> But I don't know how I should change for Expo user. (Although I don't think you are using Expo)

I couldn't make it work. Did you change anything else apart from that IF statement? Other people below that answer comment that change didn't work for them either. Weird.

**Comment by benevbright** [comment] 2019-02-03 10:53
That's too bad 😢 I really hope it works for you too. What version of RN? I tested with `/example`, which is using 0.57.8.
I only deleted 
`if (mOnScrollDispatchHelper.onScrollChanged(x, y)) {` and `}`.

**Comment by emmx** [comment] 2019-02-04 05:20
I've tried your example on my phone but I see the same result. Below is a recording of the last two screens on the example (the ones with tab navigators), the first two works fine howerver!

I'm guessing you tried one of the first?

![50209038_2040187609612751_1314244307355435008_n](https://user-images.githubusercontent.com/1238560/52190840-16514480-2820-11e9-9b5f-90564489a097.gif)

**Comment by emmx** [comment] 2019-02-04 05:53
I'm certainly missing something...

I've deleted the whole file ReactScrollView.java and also I removed the build folder from `android/app/`. Then I run `react-native run-android` and it creates a new apk so I'm guessing it compiles everything again, however I see no error whatsoever and the scrolling is still buggy. Weird, it shouldn't be working.

**Comment by benevbright** [comment] 2019-02-04 22:50
Hey, sorry @emmx 
Unfortunately, you're right. I tested again and yes, it's not fixed... 
I'm sorry about your time spending.
This should be fixed though.. It's not acceptable.

**Comment by emmx** [comment] 2019-02-05 04:35
That patch may fix the issue but I couldn't test it correctly. Somehow editing the file and running run-android again doesn't cause react-native to recompile so we still see the bug, but actually the IF is still there.

I'm opening an issue on their repository to ask more about this, I'll report back here.

**Comment by ganlanshu0211** [comment] 2019-05-31 01:53
Sorry,but I find another demo [https://github.com/austenLacy/react-native-collapsible-header-with-tabs-demo](url)

**Comment by kartikpr** [comment] 2019-08-13 18:54
@emmx I've followed you in pursuit of finding a solution to make a collapsible header like Instagram . Did you succeed in doing so?

**Comment by benevbright** [comment] 2019-08-29 20:46
Let's continue in https://github.com/benevbright/react-navigation-collapsible/issues/72 about Instagram behavior.

**Closed by benevbright** 2019-08-29 20:46 UTC
Labels: discussion, question

**Comment by mpcen** [comment] 2019-10-14 03:44
@benevbright has the lagging/stuttering issue been fixed yet with an animated header scrolled by a flatlist on Android?

**Comment by KingAmo** [comment] 2020-05-08 05:51
> I'm not using Expo so it probably works for me, thanks!

@emmx  could you please give some advice on how to implement the collapse header with tab like the gif you give ?
